### ISSUE TITLE
Unable to play music with "Play Internet Sound" admin command

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#6977]
It's pretty simple, whenever I post a link from YT it comes up with an error message like so;
```

Youtube-dl URL retrieval FAILED:

Traceback (most recent call last):
 File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
 "__main__", fname, loader, pkg_name)
 File "c:\python27\lib\runpy.py", line 72, in _run_code
 exec code in run_globals
 File "C:\Python27\Scripts\youtube-dl.exe\__main__.py", line 5, in 
ImportError: No module named youtube_dl

```
Seems like the new server thing has messed up the coding or something, unless there is some format I have to put in for the link this should be fixed.

**Comment by ghost** [comment]
Server issue, not a codebase issue (will be fixed eventually)
